server:
  port: 8091

spring:
  application:
    name: msvc-login
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/logindb
    username: postgres
    password: 123456789rC!V
    jpa:
      hibernate:
        ddl-auto: update
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect


